LabParasitologia/Exame/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path

app_name = 'exame'

urlpatterns = [
    path('adicionar/<int:pk>', views.adicionar, name='adicionar'),
    path('adicionar/<int:pk>/<int:exame>', views.adicionar_exame_amostra, name='adicionar_exame_amostra'),
    # path('DefinirResultados/<int:pk>', views.definir_resultados, name='definir_resultados'),
    path('listar/', views.listar, name='listar'),
    path('listar-inativos/', views.listar_inativos, name='listar_inativos'),
    # path('CadastrarExame/', views.CadastrarExame.as_view(), name='CadastrarExame'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar/resultados/<str:nome>/<str:tipo_resultado>', views.definir_saidas, name='resultados'),
    path('detalhes/<int:pk>', views.detalhes, name='detalhes'),
    path('detalhes/<int:pk>', views.NovoDetalheExame, name='DetalheExame'),
    path('editar/<int:pk>', views.Editar.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
    path('mudar-status/<int:status>/<int:exame>', views.mudar_status_exame, name='mudar_status_exame'),

    path('cadastrar-multiplos-resultados/<int:fase>/<int:pk>', views.cadastrar_multiplos_resultados, name='cadastrar_multiplos_resultados'),

	path('download/', views.download_exames, name='download')
]

LabParasitologia/LabParasitologia/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "home"

urlpatterns = [
    path('', include('Amostra.urls', namespace='home')),
	path('amostra/', include('Amostra.urls', namespace='amostra')),
    path('usuario/', include('Usuario.urls', namespace='usuario')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('exame/', include('Exame.urls', namespace='exame')),
    path('local/', include('Local.urls', namespace='local')),
    path('admin/', admin.site.urls),
]

LabParasitologia/Local/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
app_name = 'local'

urlpatterns = [
    url('cadastrar/', views.Cadastrar.as_view(), name='cadastrar'),
    url('listar/', views.localListar, name='listarLocal'),
    path('detalhes/<int:pk>', views.listar_amostras_local, name='listar_amostras_local'),
    path('editar/<int:pk>', views.Editar.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
]

LabParasitologia/Amostra/models.py
from django.db import models
from datetime import date
from Usuario.models import User
from Exame.models import Exame
from Local.models import Local
from datetime import datetime, date

TIPOS_AMOSTRA = [
        ('CA', 'Carrapato'),
        ('FE', 'Fezes'),
        ('MO', 'Mosca'),
        ('PI', 'Piolho'),
        ('PU', 'Pulga'),
        ('SA', 'Sangue'),
        ('OU', 'Outro'),
    ]

SEXO = [
        ('F', 'Feminino'),
        ('M', 'Masculino'),
        ('I', 'Indeterminado'),
    ]

ESPECIES_ANIMAIS = [
        ('AV', 'Aves'),
        ('BO', 'Bovino'),
        ('CA', 'Camarão'),
        ('CN', 'Canino'),
        ('CP', 'Caprino'),
        ('EQ', 'Equino'),
        ('FE', 'Felino'),
        ('PE', 'Peixe'),
        ('OV', 'Ovino'),
        ('SU', 'Suíno'),
        ('OU', 'Outro'),
    ]

class Amostra(models.Model):
    identificacao = models.CharField(max_length=10)
    origem = models.CharField(max_length=200)
    responsavel = models.ForeignKey(User, on_delete=models.CASCADE, null = True, related_name='amostras')
    localidade = models.ForeignKey(Local, on_delete=models.CASCADE, null = True, related_name='local')
    setor = models.CharField(max_length=200)
    data_coleta = models.DateField(default=date.today)
    tipo_amostra = models.CharField(max_length=2, choices=TIPOS_AMOSTRA, default='OU')
    especie_animal = models.CharField(max_length=2, choices=ESPECIES_ANIMAIS,default='OU')
    sexo_animal = models.CharField(max_length=1, choices=SEXO, default='I')
    status = models.BooleanField(default=True)
    exames = models.ManyToManyField(Exame, through='RealizacaoExame')
    created_at = models.DateField(default=date.today, null=True, blank=True)

    def __str__(self):
        return self.identificacao

    class Meta:
        ordering = ['-data_coleta','-id']



class RealizacaoExame(models.Model):

    exame = models.ForeignKey(Exame, on_delete=models.CASCADE)
    amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    resultado_numerico = models.IntegerField(null=True)
    resultado_textual = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateField(default=date.today, null=True, blank=True)
    data = models.DateField(default=date.today)

    def __str__(self):
        return "{} : {}".format(self.amostra.identificacao, self.exame.nome)

LabParasitologia/Animal/models.py
from django.db import models
from Local.models import Local

SEXO = [
        ('F', 'Feminino'),
        ('M', 'Masculino'),
        ('I', 'Indeterminado'),
    ]

ESPECIES_ANIMAIS = [
        ('AV', 'Aves'),
        ('BO', 'Bovino'),
        ('CA', 'Camarão'),
        ('CN', 'Canino'),
        ('CP', 'Caprino'),
        ('EQ', 'Equino'),
        ('FE', 'Felino'),
        ('PE', 'Peixe'),
        ('OV', 'Ovino'),
        ('SU', 'Suíno'),
        ('OU', 'Outro'),
    ]

class Animal(models.Model):
    identificacao = models.CharField(max_length=10)
    origem = models.CharField(max_length=200)
    localidade = models.ForeignKey(Local, on_delete=models.CASCADE, null = True, related_name='local')
    setor = models.CharField(max_length=200)
    especie_animal = models.CharField(max_length=2, choices=ESPECIES_ANIMAIS,default='OU')
    sexo_animal = models.CharField(max_length=1, choices=SEXO, default='I')
    situação = models.BooleanField(default=True)

    def __str__(self):
        return str(self.localidade) + "-" + self.identificacao

    class Meta:
        ordering = ('situacao', 'localidade', 'especie_animal', 'identificacao')

LabParasitologia/Local/models.py
from django.db import models

class Local(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

LabParasitologia/Local/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy

from .models import Local
from Amostra.models import Amostra

class Cadastrar(LoginRequiredMixin, generic.CreateView):
    fields = ('nome',)
    model = Local
    template_name = 'Local/cadastrarLocal.html'

    def get_success_url(self):

        if 'add' in self.request.POST:
            url = reverse_lazy('local:cadastrar')
        else:
            url = reverse_lazy('local:listarLocal')
        return url

def localListar(request):
    local = Local.objects.all()
    context = {'listar_local':local}
    return render(request, 'Local/ListarLocal.html', context)

def listar_amostras_local(request, pk):
    local = Local.objects.filter(pk=pk)
    amostra = Amostra.objects.filter(localidade_id=pk)
    context = {'loc':local, 'lista_amostra':amostra}
    return render(request, 'Local/local_detail.html', context)

class Detalhes(LoginRequiredMixin, generic.DetailView):
    model = Local
    template_name = "Local/local_detail.html"

class Editar(LoginRequiredMixin, generic.UpdateView):
    model = Local
    fields = ['nome']
    template_name = 'Local/local_update.html'

    def get_success_url(self):
        return(self.request.POST.get('next', '/'))

class Deletar(LoginRequiredMixin, generic.DeleteView):
    model = Local
    template_name = 'Local/ListarLocal.html'

    def get_success_url(self):
        return(self.request.POST.get('next', '/'))

LabParasitologia/templates/Local/ListarLocal.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block arquivos_js_css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Amostra/css/list_style.css' %}"/>
<script src="{% static 'Amostra/js/list_js.js' %}"></script>
{% endblock %}

{% block titulo %}
	Listar locais
{% endblock %}


{% block content %}
  <div class="container">

    {% if listar_local %}
       <table id="amostraDT" class="table" cellspacing="0" width="100%">
           <thead >
            <th scope="col"><center>#</center></th>
            <th><center>Nome</center></th>
            <th></th>
          </thead>
            <tbody>
               {% for local in listar_local %}
               <tr>
                   <th scope="row"><center>{{ forloop.counter }}</center></th>
                  <td><center>{{ local.nome }}</center></td>
                   <td>
                       <a href="{% url 'local:listar_amostras_local' pk=local.pk %}" class="btn btn-primary-outline" data-toggle="tooltip" title="Detalhes">
                        <i class="fa fa-search" aria-hidden="true" style="color:#165d08"></i>
                      </a>
                       <a href="{% url 'local:editar' pk=local.pk %}?next={{ request.path }}" class="btn btn-warning-outline" data-toggle="tooltip" title="Editar">
                          <i class="fas fa-pencil-alt" style="color:blue"></i>
                       </a>
                      <a href="" class="btn btn-danger-outline" data-toggle="modal" data-target="#fm-modal-grid-{{exame.pk}}"
                                        data-tt="tooltip" title="Deletar">
                       <i class="fa fa-trash" aria-hidden="true" style="color:black"></i>

                      </a>
                                 <div class="modal fade" id="fm-modal-grid-{{exame.pk}}" tabindex="-1"
                                     role="dialog" aria-labelledBy="fm-modal-grid-{{amostra.pk}}"
                                    aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                             <div class="modal-header" style="background-color: rgb(78,115,223);">
                                                <h5 class="modal-title" id=""><strong><font color="white">Deletar local</font></strong></h5>
                                                <button class="close" data-dismiss="modal" aria-label="Cerrar">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="container-fluid">
                                                    <div class="row">
                                                        <div class="col-12 col-sm-6">
                                                            <p><strong>Você tem certeza que deseja deletar o seguinte local:</strong></p>
                                                            <p>Nome: {{ local.nome }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="modal-footer" style="background-color: rgb(78,115,223);">
                                                <form action="{% url 'local:deletar' pk=local.pk %}" method="POST">
                                                       {% csrf_token %}
                                                        <input type="hidden" name="next" value="{{request.path}}">
                                                       <button class="btn btn-danger">Deletar</button>
                                                </form>
                                                <button class="btn btn-dark" data-dismiss="modal">Cancelar</button>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                   </td>
               </tr>
               {% endfor %}

            </tbody>
       </table>
    {% endif %}
  </div>
{% endblock %}

LabParasitologia/templates/Local/cadastrarLocal.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
Cadastrar Local
{% endblock %}

{% block content %}
  <div class="container">

    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" value="Cadastrar">
        <input type="submit" class="btn btn-success" name="add" value="Cadastrar e adicionar novamente" >
    </form>
  </div>
{% endblock %}

LabParasitologia/templates/Local/local_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
Local Detalhes
{% endblock %}
{% block content %}
<div class="container">
	{% if loc %}
		{% for local in loc %}
			<h5>Nome: {{ local.nome }} </h5>
            <br>
		{% endfor %}
	{% endif %}

	<h2><strong>Amostras</strong></h2>
	{% if lista_amostra %}
		{% for amostra in lista_amostra %}
			<h5>Amostra: {{ amostra.identificacao }}</h5>
			<h5>Data: {{ amostra.data_coleta }} </h5>
			<h5>Responsavel: {{ amostra.responsavel }} </h5>
			<h5>Localidade: {{ amostra.localidade }}</h5>
			<h5>Setor: {{ amostra.setor }}</h5>
    		<h5>{{ amostra.get_tipo_amostra_display }}</h5>
    		<h5>Especie: {{ amostra.get_especie_animal_display }}</h5>
    		<h5>Sexo: {{ amostra.sexo_animal }}</h5>
			<br>
		{% endfor %}
	{% else %}
		<h5>Nao há exame adicionado</h5>
	{% endif %}
  </div>



{% endblock %}

LabParasitologia/templates/Local/local_update.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
	Editar local
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="hidden" name="next" value="{{request.GET.next}}">
          <input type="submit" class="btn btn-success" name="" value="Atualizar" >
        </form>
      </div>
{% endblock %}