LabParasitologia/Exame/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path

app_name = 'exame'

urlpatterns = [
    path('adicionar/<int:pk>', views.adicionar, name='adicionar'),
    path('adicionar/<int:pk>/<int:exame>', views.adicionar_exame_amostra, name='adicionar_exame_amostra'),
    # path('DefinirResultados/<int:pk>', views.definir_resultados, name='definir_resultados'),
    path('listar/', views.listar, name='listar'),
    path('listar-inativos/', views.listar_inativos, name='listar_inativos'),
    # path('CadastrarExame/', views.CadastrarExame.as_view(), name='CadastrarExame'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar/resultados/<str:nome>/<str:tipo_resultado>', views.definir_saidas, name='resultados'),
    path('detalhes/<int:pk>', views.detalhes, name='detalhes'),
    path('detalhes/<int:pk>', views.NovoDetalheExame, name='DetalheExame'),
    path('editar/<int:pk>', views.Editar.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
    path('mudar-status/<int:status>/<int:exame>', views.mudar_status_exame, name='mudar_status_exame'),

    path('cadastrar-multiplos-resultados/<int:fase>/<int:pk>', views.cadastrar_multiplos_resultados, name='cadastrar_multiplos_resultados'),

	path('download/', views.download_exames, name='download')
]

LabParasitologia/LabParasitologia/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "home"

urlpatterns = [
    path('', include('Amostra.urls', namespace='home')),
	path('amostra/', include('Amostra.urls', namespace='amostra')),
    path('usuario/', include('Usuario.urls', namespace='usuario')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('exame/', include('Exame.urls', namespace='exame')),
    path('local/', include('Local.urls', namespace='local')),
    path('admin/', admin.site.urls),
]

LabParasitologia/Amostra/models.py
from django.db import models
from datetime import date
from Usuario.models import User
from Exame.models import Exame
from Local.models import Local
from datetime import datetime, date

TIPOS_AMOSTRA = [
        ('CA', 'Carrapato'),
        ('FE', 'Fezes'),
        ('MO', 'Mosca'),
        ('PI', 'Piolho'),
        ('PU', 'Pulga'),
        ('SA', 'Sangue'),
        ('OU', 'Outro'),
    ]

SEXO = [
        ('F', 'Feminino'),
        ('M', 'Masculino'),
        ('I', 'Indeterminado'),
    ]

ESPECIES_ANIMAIS = [
        ('AV', 'Aves'),
        ('BO', 'Bovino'),
        ('CA', 'Camarão'),
        ('CN', 'Canino'),
        ('CP', 'Caprino'),
        ('EQ', 'Equino'),
        ('FE', 'Felino'),
        ('PE', 'Peixe'),
        ('OV', 'Ovino'),
        ('SU', 'Suíno'),
        ('OU', 'Outro'),
    ]

class Amostra(models.Model):
    identificacao = models.CharField(max_length=10)
    origem = models.CharField(max_length=200)
    responsavel = models.ForeignKey(User, on_delete=models.CASCADE, null = True, related_name='amostras')
    localidade = models.ForeignKey(Local, on_delete=models.CASCADE, null = True, related_name='local')
    setor = models.CharField(max_length=200)
    data_coleta = models.DateField(default=date.today)
    tipo_amostra = models.CharField(max_length=2, choices=TIPOS_AMOSTRA, default='OU')
    especie_animal = models.CharField(max_length=2, choices=ESPECIES_ANIMAIS,default='OU')
    sexo_animal = models.CharField(max_length=1, choices=SEXO, default='I')
    status = models.BooleanField(default=True)
    exames = models.ManyToManyField(Exame, through='RealizacaoExame')
    created_at = models.DateField(default=date.today, null=True, blank=True)

    def __str__(self):
        return self.identificacao

    class Meta:
        ordering = ['-data_coleta','-id']



class RealizacaoExame(models.Model):

    exame = models.ForeignKey(Exame, on_delete=models.CASCADE)
    amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    resultado_numerico = models.IntegerField(null=True)
    resultado_textual = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateField(default=date.today, null=True, blank=True)
    data = models.DateField(default=date.today)

    def __str__(self):
        return "{} : {}".format(self.amostra.identificacao, self.exame.nome)

LabParasitologia/Animal/models.py
from django.db import models
from Local.models import Local

SEXO = [
        ('F', 'Feminino'),
        ('M', 'Masculino'),
        ('I', 'Indeterminado'),
    ]

ESPECIES_ANIMAIS = [
        ('AV', 'Aves'),
        ('BO', 'Bovino'),
        ('CA', 'Camarão'),
        ('CN', 'Canino'),
        ('CP', 'Caprino'),
        ('EQ', 'Equino'),
        ('FE', 'Felino'),
        ('PE', 'Peixe'),
        ('OV', 'Ovino'),
        ('SU', 'Suíno'),
        ('OU', 'Outro'),
    ]

class Animal(models.Model):
    identificacao = models.CharField(max_length=10)
    origem = models.CharField(max_length=200)
    localidade = models.ForeignKey(Local, on_delete=models.CASCADE, null = True, related_name='local')
    setor = models.CharField(max_length=200)
    especie_animal = models.CharField(max_length=2, choices=ESPECIES_ANIMAIS,default='OU')
    sexo_animal = models.CharField(max_length=1, choices=SEXO, default='I')
    situação = models.BooleanField(default=True)

    def __str__(self):
        return str(self.localidade) + "-" + self.identificacao

    class Meta:
        ordering = ('situacao', 'localidade', 'especie_animal', 'identificacao')

LabParasitologia/Exame/models.py
from django.db import models
from datetime import datetime, date
from django.utils import timezone

TIPOS_RESULTADO = [
    ('NUM', 'Numérico'),
    ('TEX', 'Valores exatos')
]

class Exame(models.Model):
    nome = models.CharField(max_length=200, unique=True)
    status = models.BooleanField(default=True)
    tipo_resultado = models.CharField(max_length=3, choices=TIPOS_RESULTADO, default='NUM', null=True)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ('nome',)



class ResultadoExame(models.Model):
    resultado_textual = models.CharField(max_length=200, blank=True, null=True)
    resultado_numerico = models.IntegerField(blank=True, null=True)
    ordem = models.PositiveIntegerField(blank=True, null=True)
    exame = models.ForeignKey(Exame, on_delete=models.CASCADE, related_name='resultados')

    def __str__(self):
        return "{}".format(self.exame.nome)

    class Meta:
        ordering = ['exame']

LabParasitologia/Exame/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime, date, timedelta

from django.contrib import messages

import json
import csv

from .forms import especieForm
from .forms import ExameForm, RealizacaoExameForm, ResultadoFormNumerico, ResultadoFormTextual
from .forms import ResultadoTextualFormset, ResultadoNumericoFormset

from .models import Exame, ResultadoExame
from Amostra.models import Amostra, RealizacaoExame

def listar(request):
    exame_list = Exame.objects.filter(status=True)
    paginator = Paginator(exame_list, 5)

    page = request.GET.get('page')
    exame = paginator.get_page(page)
    context = {'listar_exame':exame}
    return render(request, 'Exame/ListarExame.html', context)

def detalhes(request, pk):
    exame = Exame.objects.filter(pk=pk)[0]
    resultados_exame = RealizacaoExame.objects

    ultimo_12 = []
    exames_mes = []
    mes_atual = date.today().month
    ano_atual = date.today().year-1

    for i in range(1, 13):
        mes_atual += 1
        if (mes_atual == 13):
            mes_atual = 1
        if (mes_atual == 1):
            ano_atual += 1
        exames_passados = RealizacaoExame.objects.filter(exame=exame, data__month = mes_atual, data__year = ano_atual)
        exames_mes.insert(i, exames_passados.count())
        ultimo_12.insert(i, str(mes_atual)+"/"+str(ano_atual))
    


    informacoes = {
        'exame': exame,
        'exames_mes': json.dumps(exames_mes),
        'ultimo_12': json.dumps(ultimo_12)
    }
    return render(request, 'Exame/detalhes.html', informacoes)

#class AdicionarExame(LoginRequiredMixin, generic.CreateView):
#    fields = ('exame','resultado')
#    model = RealizacaoExame
#    template_name = 'Exame/AdicionarExame.html'

#    def form_valid(self, form):
#        amostra = Amostra.objects.filter(pk=pk)
#        form.instance.amostra = amostra
#        return super(AdicionarExame, self).form_valid(form)
#
#    def get_success_url(self):
#
#        if 'add' in self.request.POST:
#            url = reverse_lazy('exame:adicionar')
#        else:
#            url = reverse_lazy('amostra:listar')

#        return url

def adicionar(request, pk):
    amostra = Amostra.objects.get(pk=pk)
    if request.method == "POST":
        exame_form = RealizacaoExameForm(request.POST)
    else:
        exame_form = RealizacaoExameForm(tipo="NUM")

    if exame_form.is_valid():
        exame_form.instance.amostra = amostra
        RealizacaoExame = exame_form.save()
        RealizacaoExame.save()
        if 'add' in request.POST:
            return redirect('exame:adicionar', pk)
        else:
            return redirect('amostra:detalhes', pk)
    else:
        print(exame_form.errors)
    return render(request, 'Exame/AdicionarExame.html',
                  {'exame_form': exame_form, 'amostra':amostra})

def adicionar_exame_amostra(request, pk, exame):
    amostra = Amostra.objects.get(pk=pk)
    exame_cadastrar = Exame.objects.get(pk=exame)
    tipo = exame_cadastrar.tipo_resultado
    possiveis_resultados = ResultadoExame.objects.filter(exame=exame)

    if request.method == "POST":
        exame_form = RealizacaoExameForm(request.POST, tipo=tipo, exame=exame)
    else:
        exame_form = RealizacaoExameForm(tipo=tipo, exame=exame)

    if exame_form.is_valid():
        exame_form.instance.amostra = amostra
        exame_form.instance.exame = exame_cadastrar
        RealizacaoExame = exame_form.save()
        RealizacaoExame.save()
        if 'add' in request.POST:
            return redirect('exame:adicionar', pk)
        else:
            return redirect('amostra:detalhes', pk)
    return render(request, 'Exame/AdicionarExame.html',
                  {'form': exame_form, 'amostra':amostra, 'tipo': tipo, 'exame': exame_cadastrar})


class CadastrarExame(LoginRequiredMixin, generic.CreateView):
    fields = ('nome','tipo_resultado')
    model = Exame
    template_name = 'Exame/CadastrarExame.html'

    def get_success_url(self):
        if 'add' in self.request.POST:
            url = reverse_lazy('exame:CadastrarExame')
        else:
            url = reverse_lazy('exame:definir_resultados', kwargs={'pk': self.object.id})
        return url

def cadastrar(request):
    if request.method == "POST":
        exame_form = ExameForm(request.POST)
        if exame_form.is_valid():
            nome = exame_form.cleaned_data['nome']
            tipo_resultado = exame_form.cleaned_data['tipo_resultado']
            return redirect('exame:resultados', nome, tipo_resultado)
        else:
            print(exame_form.errors)
    else:
        exame_form = ExameForm()
    
    
    return render(request, 'Exame/CadastrarExame.html',
                  {'form': exame_form})

def definir_saidas(request, nome, tipo_resultado):
    template_name = 'Exame/DefinirResultados.html'
    i=0
    if tipo_resultado == "NUM":
        if request.method == 'GET':
            formset = ResultadoNumericoFormset(request.GET or None)
        elif request.method == 'POST':
            formset = ResultadoNumericoFormset(request.POST)
            if formset.is_valid():
                exame = Exame(nome=nome, tipo_resultado=tipo_resultado)
                exame.save()
                for count, form in enumerate(formset, start=1):
                    valor = form.cleaned_data.get('valor')
                    if valor:
                        ResultadoExame(resultado_numerico=valor, exame=exame, ordem=i).save()
                        i=i+1
                return redirect('exame:listar')
        return render(request, template_name, {
            'formset': formset, 'tipo': 'NUM', 'nome': nome
        })
    else:
        if request.method == 'GET':
            formset = ResultadoTextualFormset(request.GET or None)
        elif request.method == 'POST':
            formset = ResultadoTextualFormset(request.POST)
            if formset.is_valid():
                # is_empty = False
                # for form in formset:
                #     if not form.cleaned_data.get('valor'):
                #         is_empty = True
                #         messages.error(request, 'Document deleted.')
                # if not is_empty:
                    exame = Exame(nome=nome, tipo_resultado=tipo_resultado)
                    exame.save()
                    for count, form in enumerate(formset, start=1):
                        valor = form.cleaned_data.get('valor')
                        if valor:
                            ResultadoExame(resultado_textual=valor, exame=exame, ordem=count).save()
                    return redirect('exame:listar')    
        return render(request, template_name, {'formset': formset, 'tipo': 'TEX', 'nome': nome})    

def definir_resultados(request,pk):
    template_name = 'Exame/DefinirResultados.html'
    exame = Exame.objects.get(pk=pk)
    i=0
    if exame.tipo_resultado == "NUM":
        if request.method == 'GET':
            formset = ResultadoNumericoFormset(request.GET or None)
        elif request.method == 'POST':
            print("post")
            formset = ResultadoNumericoFormset(request.POST)
            if formset.is_valid():
                print("valid")
                for count, form in enumerate(formset, start=1):
                    valor = form.cleaned_data.get('valor')
                    if valor:
                        ResultadoExame(resultado_numerico=valor, exame=exame, ordem=i).save()
                        i=i+1
                return redirect('exame:listar')
        print("not valid")
        return render(request, template_name, {
            'formset': formset, 'tipo': 'NUM',
        })
    else:
        if request.method == 'GET':
            formset = ResultadoTextualFormset(request.GET or None)
        elif request.method == 'POST':
            formset = ResultadoTextualFormset(request.POST)
            if formset.is_valid():
                for count, form in enumerate(formset, start=1):
                    valor = form.cleaned_data.get('valor')
                    if valor:
                        ResultadoExame(resultado_textual=valor, exame=exame, ordem=count).save()
                return redirect('exame:listar')
        return render(request, template_name, {
            'formset': formset, 'tipo': 'TEX',
        })

class DetalheExame(LoginRequiredMixin, generic.DetailView):
    model = Exame
    template_name = "Exame/exame_detail.html"

def monthdelta(date, delta):
    m, y = (date.month+delta) % 12, date.year + ((date.month)+delta-1) // 12
    if not m: m = 12
    d = min(date.day, [31,
        29 if y%4==0 and not y%400==0 else 28,31,30,31,30,31,31,30,31,30,31][m-1])
    return date.replace(day=d,month=m, year=y)

def encontrarCategoria(resultado, categorias, tipo):
    if tipo == 'NUM':
        for i in range(len(categorias)):
            if i == 0 and resultado <= categorias[i]:
                return i
            elif i == (len(categorias)-1) and resultado > categorias[i]:
                return i+1
            elif i != (len(categorias)-1) and resultado > categorias[i] and resultado <= categorias[i+1]:
                return i+1
    else:
        try:
            return categorias.index(resultado)
        except ValueError:
            return -1

def NovoDetalheExame(request, pk):
    nome = Exame.objects.filter(pk=pk)
    tipo = nome[0].tipo_resultado
    categorias = []
    for cat in nome[0].resultados.all():
        if tipo == 'NUM':
            categorias.append(cat.resultado_numerico)
        else:
            categorias.append(cat.resultado_textual)
    valores = [0,0,0,0,0]
    exames = RealizacaoExame.objects.filter(exame_id=pk)

    print("Categorias")
    print(categorias)

LabParasitologia/templates/Exame/AdicionarExame.html
{% extends "base.html" %}

{% load crispy_forms_tags %}  

{% block titulo %}
 Cadastrar resultado de exame {{exame}}

{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Data da coleta</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{amostra.data_coleta|date:"d/m/Y"}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Localidade</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{amostra.localidade}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-map-marked-alt fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-secondary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">Origem</div>
            <div class="row no-gutters align-items-center">
            <div class="col-auto">
              <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{amostra.origem}}</div>
            </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-warehouse fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>

      <!-- Pending Requests Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Setor</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{amostra.setor}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-vector-square fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>
      </div>

      <div class="row">

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Espécie</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{amostra.get_especie_animal_display}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-paw fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-dark shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">Tipo de amostra</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{amostra.get_tipo_amostra_display}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-syringe fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Sexo do animal</div>
            <div class="row no-gutters align-items-center">
            <div class="col-auto">
              <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{amostra.get_sexo_animal_display}}</div>
            </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-venus-mars fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>

      <!-- Pending Requests Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Responsável</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{amostra.responsavel}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-user fa-2x text-gray-300"></i>
          </div>
          </div>
        </div>
        </div>
      </div>
	  </div>
  </div>
  <div class="container">

    <form method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-6">
          {{ form.data|as_crispy_field }}
        </div>
        <div class="col-6">
          {% if tipo == "TEX" %}
            {{ form.resultado_textual|as_crispy_field }}
          {% else %}
            {{ form.resultado_numerico|as_crispy_field }}
          {% endif %}
        </div>
      </div>
      <input type="submit" class="btn btn-success" value="Adicionar">
    </form>
  </div>
{% endblock %}

LabParasitologia/templates/Exame/ListarExame.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block arquivos_js_css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Amostra/css/list_style.css' %}"/>
<script src="{% static 'Amostra/js/list_js.js' %}"></script>
{% endblock %}

{% block titulo %}
	Listar Exame
{% endblock %}


{% block content %}


  <!-- <div class="container"> -->
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script type="text/javascript" src="includes/upload/jquery-1.4.2.min.js"></script>

      <script type = "text/javascript">
        function carregar(pagina){
            $("#conteudo").load(pagina);
        }
      </script>



    {% if listar_exame %}
       <table id="dataTable" class="table" cellspacing="0" width="100%">
           <thead >
            <th scope="col"><font><center>#</center></font></th>
            <th><font></font><center>Nome</center></font></th>
            <th></th>
          </thead>
            <tbody>
               {% for exame in listar_exame %}

               <tr>
                   <th scope="row"><font></font><center>{{ forloop.counter }}</center></font></th>
                  <td><font></font><center>{{ exame.nome }}</center></font></td>
                   <td>
                      <a href="{% url 'exame:detalhes' pk=exame.pk %}" class="btn btn-primary-outline" data-toggle="tooltip" title="Detalhes">
                        <i class="fa fa-search" aria-hidden="true" style="color:#1cc88a"></i>
                      </a>
                       <a href="{% url 'exame:editar' pk=exame.pk %}?next={{ request.path }}" class="btn btn-warning-outline" data-toggle="tooltip" title="Editar">
                          <i class="fas fa-pencil-alt" style="color:#4e73df"></i>
                       </a>
                      <a href="" class="btn btn-danger-outline" data-toggle="modal" data-target="#fm-modal-grid-{{exame.pk}}"
                                        data-tt="tooltip" title="Deletar">
                      <i class="fa fa-times" aria-hidden="true" style="color:#e74a3b"></i>

                      </a>
                                 <div class="modal fade" id="fm-modal-grid-{{exame.pk}}" tabindex="-1"
                                     role="dialog" aria-labelledBy="fm-modal-grid-{{amostra.pk}}"
                                    aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <div class="modal-header" style="background-color: rgb(78,115,223);">
                                                <h5 class="modal-title" id=""><strong><font color="white">Desativar exame</font></strong></h5>
                                                <button class="close" data-dismiss="modal" aria-label="Cerrar">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="container-fluid">
                                                    <div class="row">
                                                        <div class="col-12 col-sm-6">
                                                            <p><strong>Você tem certeza que deseja desativar o seguinte exame:</strong></p>
                                                            <p>Nome: {{ exame.nome }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="modal-footer" style="background-color: rgb(78,115,223);">
                                                <form action="{% url 'exame:mudar_status_exame' status=0 exame=exame.pk %}" method="POST">
                                                       {% csrf_token %}
                                                        <input type="hidden" name="next" value="{{request.path}}">
                                                       <button class="btn btn-danger">Desativar</button>
                                                </form>
                                                <button class="btn btn-dark" data-dismiss="modal">Cancelar</button>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                   </td>
               </tr>
               {{ exame.full_name|upper }}
               {% endfor %}

            </tbody>
       </table>

    {% else %}
      <p>Não há exames cadastrados ou ativos no sistema</p>
    {% endif %}

      <div class="pagination">
        <span class="step-links">
             <nav aria-label="Navegação de página exemplo">
                 <ul class="pagination">
                    {% if listar_exame.has_previous %}
                        <a class="page-link" href="?page=1">&laquo; Primeiro</a>
                        <a class="page-link" href="?page={{ listar_exame.previous_page_number }}">Anterior</a>
                    {% endif %}

                    {% if listar_exame.has_next %}
                        <a class="page-link" href="?page={{ listar_exame.next_page_number }}">Proximo</a>
                        <a class="page-link" href="?page={{ listar_exame.paginator.num_pages }}">Ultimo &raquo;</a>
                    {% endif %}
                 </ul>
             </nav>
        </span>
    </div>
        <span class="current" >
         <center> Página {{ listar_exame.number }} de {{ listar_exame.paginator.num_pages }}.</center>
        </span>
        <br>

      <div id="conteudo"></div>


  <!-- </div> -->
{% endblock %}

LabParasitologia/templates/Exame/detalhes.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
Exame {{exame.nome}}
{% endblock %}


{% block content %}

{% endblock %}

LabParasitologia/templates/Exame/exame_update.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
Editar exame
{% endblock %}

{% block content %}


    <div class="container">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="hidden" name="next" value="{{request.GET.next}}">
          <input type="submit" class="btn btn-success" name="" value="Atualizar" >
        </form>
      </div>
{% endblock %}