LabParasitologia/Amostra/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'amostra'

urlpatterns = [
	path('home/', views.home, name='home'),

	path('', views.home, name='home'),
	path('listar/', views.listar, name='listar'),
	path('listar/finalizadas', views.listar_finalizadas, name='listar_finalizadas'),
	path('listar/usuario/<int:pk>', views.listar_amostras_usuario, name='listar_amostras_usuario'),
	path('listar/finalizadas/usuario/<int:pk>', views.listar_amostras_finalizadas_usuario, name='listar_amostras_finalizadas_usuario'),

	path('cadastrar/', views.cadastrar, name='cadastrar'),
	path('detalhes/<int:pk>', views.detalhes, name='detalhes'),
	path('editar/<int:pk>', views.Editar.as_view(), name='editar'),
	path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
	
	path('mudar-status/<int:status>/<int:amostra>', views.mudar_status, name='mudar_status'),
	path('alertas/', views.listar_alertas, name='listar_alertas'),

	path('download/', views.download_amostras, name='download')

]

LabParasitologia/Exame/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path

app_name = 'exame'

urlpatterns = [
    path('adicionar/<int:pk>', views.adicionar, name='adicionar'),
    path('adicionar/<int:pk>/<int:exame>', views.adicionar_exame_amostra, name='adicionar_exame_amostra'),
    # path('DefinirResultados/<int:pk>', views.definir_resultados, name='definir_resultados'),
    path('listar/', views.listar, name='listar'),
    path('listar-inativos/', views.listar_inativos, name='listar_inativos'),
    # path('CadastrarExame/', views.CadastrarExame.as_view(), name='CadastrarExame'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar/resultados/<str:nome>/<str:tipo_resultado>', views.definir_saidas, name='resultados'),
    path('detalhes/<int:pk>', views.detalhes, name='detalhes'),
    path('detalhes/<int:pk>', views.NovoDetalheExame, name='DetalheExame'),
    path('editar/<int:pk>', views.Editar.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
    path('mudar-status/<int:status>/<int:exame>', views.mudar_status_exame, name='mudar_status_exame'),

    path('cadastrar-multiplos-resultados/<int:fase>/<int:pk>', views.cadastrar_multiplos_resultados, name='cadastrar_multiplos_resultados'),

	path('download/', views.download_exames, name='download')
]

LabParasitologia/LabParasitologia/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "home"

urlpatterns = [
    path('', include('Amostra.urls', namespace='home')),
	path('amostra/', include('Amostra.urls', namespace='amostra')),
    path('usuario/', include('Usuario.urls', namespace='usuario')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('exame/', include('Exame.urls', namespace='exame')),
    path('local/', include('Local.urls', namespace='local')),
    path('admin/', admin.site.urls),
]

LabParasitologia/Local/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
app_name = 'local'

urlpatterns = [
    url('cadastrar/', views.Cadastrar.as_view(), name='cadastrar'),
    url('listar/', views.localListar, name='listarLocal'),
    path('detalhes/<int:pk>', views.listar_amostras_local, name='listar_amostras_local'),
    path('editar/<int:pk>', views.Editar.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
]

LabParasitologia/Usuario/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
app_name = 'usuario'

urlpatterns = [
    url('login/', auth_views.LoginView.as_view(template_name='Usuario/login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url('cadastrar/', views.Cadastrar.as_view(), name='cadastrar'),
    path('editar/<int:pk>', views.Editar.as_view(), name = 'editar'),
    url('listar/', views.listar, name='listar'),
    url('listar-inativos/', views.listar_inativos, name='listar_inativos'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
    path('detalhes/<int:pk>', views.Detalhes.as_view(), name='detalhes'),
    path('mudar-status-coordenacao/<int:coord_status>/<int:usuario>', views.mudar_coordenacao_status, name='mudar_coordenacao_status'),
    path('mudar-status-ativo/<int:ativo_status>/<int:usuario>', views.mudar_ativo_status, name='mudar_ativo_status'),
]

LabParasitologia/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Lab. de Parasitologia</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->

  <link rel="stylesheet" type="text/css" href="{% static 'css/sb-admin-2.css' %}" />
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
     {% if user.is_authenticated %}
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home:home' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-microscope"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Lab. de Parasitologia</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'amostra:home' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Home</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Amostras
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'amostra:cadastrar' %}">
          <i class="fas fa-plus"></i>
          <span>Cadastrar</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'amostra:listar' %}">
          <i class="fas fa-vials"></i>
          <span>Listar</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'amostra:listar_amostras_usuario' pk=user.pk %}">
          <i class="fas fa-vial"></i>
          <span>Minhas amostras</span>
        </a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      {% if user.is_superuser %}
      <!-- Heading -->
      <div class="sidebar-heading">
        Exames
      </div>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'exame:cadastrar' %}">
          <i class="fas fa-plus"></i>
          <span>Cadastrar</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'exame:listar' %}">
          <i class="fas fa-clipboard-list"></i>
          <span>Listar</span>
        </a>
      </li>

       <hr class="sidebar-divider">


       <div class="sidebar-heading">
        Usuários
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'usuario:cadastrar' %}">
          <i class="fas fa-plus"></i>
          <span>Cadastrar</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'usuario:listar' %}">
          <i class="fas fa-users"></i>
          <span>Listar</span>
        </a>
      </li>

       <hr class="sidebar-divider">

      <div class="sidebar-heading">
        Local
      </div>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'local:cadastrar' %}">
          <i class="fas fa-plus"></i>
          <span>Cadastrar</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'local:listarLocal' %}">
          <i class="fa fa-clipboard-list"></i>
          <span>Listar</span>
        </a>
      </li>





      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      {% endif %}
      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Alerts -->

            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">{{ amostras_pendentes_count }}</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Central de Alertas
                </h6>

                  {% for amostra in amostras_pendentes|slice:"3" %}

                    <a class="dropdown-item d-flex align-items-center" href="{% url 'amostra:detalhes' pk=amostra.pk%}">
                      <div class="mr-3">
                        <div class="icon-circle bg-warning">
                          <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                      </div>
                      <div>
                       <form action="{% url 'amostra:listar_alertas' %}" method="POST">
                        <div class="small text-gray-500"></div>
                        A amostra <b>{{amostra.origem }} ({{amostra.localidade}}): {{ amostra.identificacao }}</b> cadastrada em
                         <b>{{ amostra.data_coleta|date:"d/m/y" }}</b> ainda não foi concluída.
                       </form>
                      </div>
                    </a>
                  {% endfor %}

                <a class="dropdown-item text-center small text-gray-500" href="{% url 'amostra:listar_alertas' %}">Mostrar todos</a>
              </div>
            </li>


            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.first_name}} {{user.last_name}}</span>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'usuario:editar' pk=user.pk %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Minha conta
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'usuario:logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Sair
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->
        {% endif %}

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">
              <strong>
              {% block titulo %}
              
              {% endblock %}
              </strong>
            </h1>

            <div>
              {% block titulo_lateral %}
              {% endblock %}
            </div>
          </div>

          {% block content %}
          <!--Dentro dele, sempre usar <div class="row"> para separar elementos em uma mesma linha-->
          {% endblock %}
          <!-- Content Row -->

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span> Laboratório de Parasitologia Animal EAJ/UFRN</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'usuario:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  {% block extra_js %}
  {% endblock %}

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

  <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>

LabParasitologia/templates/base_antigo.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Laboratório de Parasitologia</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <!-- Datatable -->
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
   <!--<link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.0/css/jquery.dataTables_themeroller.css">-->
   <!--<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.min.js"></script>-->
   <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">-->
	<!--<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>-->
	<!--<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>-->

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Liu+Jian+Mao+Cao|Montserrat&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    {% block arquivos_js_css %}
    {% endblock %}

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mynav" role="navigation" id='navbar'>
      <div class="container">
        <a class="navbar-brand bigbrand" href="{% url 'amostra:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Amostras
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'amostra:cadastrar' %}">Cadastrar</a>

                  <div class="dropdown-divider"></div>
                  <a class="">
                    <strong><center>Todas amostras</center></strong>
                  </a>

                  <div class="dropdown-submenu" >
                    <a class="dropdown-item" href="{% url 'amostra:listar' %}">Abertas</a>
                    <a class="dropdown-item" href="{% url 'amostra:listarFinalizada' %}">Finalizadas</a>

                   </div>

                  <div class="dropdown-divider"></div>
                  <a>
                    <center><strong>Minhas amostras</strong></center>
                  </a>

                   <div class="dropdown-submenu" >
                    <a class="dropdown-item" href="{% url 'amostra:listar_amostras_usuario' pk=user.pk %}">Abertas</a>
                    <a class="dropdown-item" href="{% url 'amostra:listar_amostras_finalizadas_usuario' pk=user.pk %}">Finalizadas</a>

                   </div>

                </div>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="examesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Exames
                  </a>
                  <div class="dropdown-menu" aria-labelledby="examesDropdown">
                    <a class="dropdown-item" href="{% url 'exame:CadastrarExame' %}">Cadastrar</a>
                    <a class="dropdown-item" href="{% url 'exame:listar' %}">Listar</a>
                  </div>
                </li>
              {% if user.is_superuser %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Usuários
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'usuario:listar' %}">Listar</a>
                    <a class="dropdown-item" href="{% url 'usuario:cadastrar' %}">Cadastrar</a>
                    <a class="dropdown-item" href="{% url 'usuario:listar_inativos' %}">Usuários inativos</a>
                  </div>
                </li>
              {% endif %}
            {% endif %}
          </ul>
          <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
            {% if user.is_authenticated %}
              <li class="nav-item active"><a class="nav-link" href="{% url 'usuario:editar' pk=user.pk %}">{{user.first_name}} {{user.last_name}}</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'usuario:logout' %}">Sair</a></li>
            {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'usuario:login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>