LabParasitologia/Exame/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path

app_name = 'exame'

urlpatterns = [
    path('adicionar/<int:pk>', views.adicionar, name='adicionar'),
    path('adicionar/<int:pk>/<int:exame>', views.adicionar_exame_amostra, name='adicionar_exame_amostra'),
    # path('DefinirResultados/<int:pk>', views.definir_resultados, name='definir_resultados'),
    path('listar/', views.listar, name='listar'),
    path('listar-inativos/', views.listar_inativos, name='listar_inativos'),
    # path('CadastrarExame/', views.CadastrarExame.as_view(), name='CadastrarExame'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar/resultados/<str:nome>/<str:tipo_resultado>', views.definir_saidas, name='resultados'),
    path('detalhes/<int:pk>', views.detalhes, name='detalhes'),
    path('detalhes/<int:pk>', views.NovoDetalheExame, name='DetalheExame'),
    path('editar/<int:pk>', views.Editar.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
    path('mudar-status/<int:status>/<int:exame>', views.mudar_status_exame, name='mudar_status_exame'),

    path('cadastrar-multiplos-resultados/<int:fase>/<int:pk>', views.cadastrar_multiplos_resultados, name='cadastrar_multiplos_resultados'),

	path('download/', views.download_exames, name='download')
]

LabParasitologia/LabParasitologia/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "home"

urlpatterns = [
    path('', include('Amostra.urls', namespace='home')),
	path('amostra/', include('Amostra.urls', namespace='amostra')),
    path('usuario/', include('Usuario.urls', namespace='usuario')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('exame/', include('Exame.urls', namespace='exame')),
    path('local/', include('Local.urls', namespace='local')),
    path('admin/', admin.site.urls),
]

LabParasitologia/Usuario/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
app_name = 'usuario'

urlpatterns = [
    url('login/', auth_views.LoginView.as_view(template_name='Usuario/login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url('cadastrar/', views.Cadastrar.as_view(), name='cadastrar'),
    path('editar/<int:pk>', views.Editar.as_view(), name = 'editar'),
    url('listar/', views.listar, name='listar'),
    url('listar-inativos/', views.listar_inativos, name='listar_inativos'),
    path('deletar/<int:pk>', views.Deletar.as_view(), name='deletar'),
    path('detalhes/<int:pk>', views.Detalhes.as_view(), name='detalhes'),
    path('mudar-status-coordenacao/<int:coord_status>/<int:usuario>', views.mudar_coordenacao_status, name='mudar_coordenacao_status'),
    path('mudar-status-ativo/<int:ativo_status>/<int:usuario>', views.mudar_ativo_status, name='mudar_ativo_status'),
]

LabParasitologia/Usuario/models.py
from django.db import models
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):


    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    class Meta:
        ordering = ['first_name', 'last_name']

LabParasitologia/Usuario/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from .models import User
from django import forms
from django.forms import ModelForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        model = User

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].label = 'Nome'
        self.fields['last_name'].label = 'Sobrenome'
        self.fields['username'].label = 'Nome de usuário'
        self.fields['email'].label = 'Email'
        self.fields['password1'].label = 'Senha'
        self.fields['password2'].label = 'Confirmar senha'

class EditarUsuarioForm(ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar senha', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("As senhas estão incorretas.")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(EditarUsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        # user.active = False # send confirmation email
        if commit:
            user.save()
        return user

LabParasitologia/Usuario/views.py
from django.views.generic import CreateView
from django.views import generic
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from . import forms
from .models import User

class Cadastrar(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('usuario:listar')
    template_name = 'Usuario/cadastrar.html'


class Editar(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = forms.EditarUsuarioForm
    template_name = 'Usuario/editarUsuario.html'
    success_url = reverse_lazy('usuario:listar')

@login_required
def listar(request):
    user = User.objects.filter(is_active=True)
    context = {'lista_user':user}
    return render(request, 'Usuario/listarUser.html', context)

class Detalhes(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = "Usuario/user_detail.html"

class Deletar(LoginRequiredMixin, generic.DeleteView):
    model = User
    template_name = 'Usuario/listarUser.html'
    success_url = reverse_lazy('usuario:listar')

def mudar_coordenacao_status(request, coord_status, usuario):
    user = User.objects.get(pk=usuario)
    if (coord_status==1):
        user.is_superuser = True
    else:
        user.is_superuser = False
    user.save()
    return redirect('usuario:listar')

def mudar_ativo_status(request, ativo_status, usuario):
    user = User.objects.get(pk=usuario)
    if (ativo_status==1):
        user.is_active = True
    else:
        user.is_active = False
    user.save()
    return redirect('usuario:listar')

@login_required
def listar_inativos(request):
    user = User.objects.filter(is_active=False)
    context = {'lista_user':user}
    return render(request, 'Usuario/usuarios_inativos.html', context)

LabParasitologia/templates/Usuario/cadastrar.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
Cadastro de usuário
{% endblock %}

{% block content %}
            <div class="container">
                      <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-success" name="" value="Cadastrar">
                      </form>
            </div>

{% endblock %}

LabParasitologia/templates/Usuario/deletar_user.html
{% extends "base.html" %}

{% block titulo %}
	Deletar Usuario
{% endblock %}


{% block content %}

    <form method="post">
        {% csrf_token %}
    <h5>Você tem certeza que deseja deletar o usuario?</h5>
        <p><b>Usuario:</b> {{ object.username }}</p>
        <p><b>Nome:</b> {{ object.first_name }} {{ object.last_name }}</p>
        <p><b>E-mail:</b> {{ object.email }}</p>
    <button type="submit" class="btn btn-success">Confirmar</button>
</form>
{% endblock %}

LabParasitologia/templates/Usuario/editarUsuario.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
	Informações do Perfil
{% endblock %}


{% block content %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success">Atualizar</button>
        </form>



{% endblock %}

LabParasitologia/templates/Usuario/listarUser.html
{% extends "base.html" %}

{% block arquivos_js_css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Amostra/css/list_style.css' %}"/>
<script src="{% static 'Amostra/js/list_js.js' %}"></script>
{% endblock %}

{% block titulo %}
	Usuários
{% endblock %}

{% block content %}



    {% if lista_user %}
         <table id="userDT" class="table" cellspacing="0" width="100%">
          <thead >
            <th scope="col"><center>#</center></th>
            <th><center>Nome</center></th>
            <th><center>Usuário</center></th>
            <th><center>E-mail</center></th>
            <th><center>Administrador</center></th>
            <th></th>
          </thead>

             <tbody>
             {% for user in lista_user %}
                <tr>
                 <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ user }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email}}</td>
                    {% if user.is_superuser %}
                    <td><center>
                        <a href="{% url 'usuario:mudar_coordenacao_status' coord_status=0 usuario=user.pk %}" class="btn btn-primary-outline"><i class="fa fa-check" aria-hidden="true" style="color:green"></i></a>
                    </center></td>
                  {% else %}
                    <td><center>
                        <a href="{% url 'usuario:mudar_coordenacao_status' coord_status=1 usuario=user.pk %}" class="btn btn-danger-outline"><i class="fa fa-times" aria-hidden="true" style="color:red"></i></a>
                    </center></td>
                  {% endif %}
                    <td>
                        <a href="{% url 'usuario:editar' pk=user.pk %}" class="btn btn-warning-outline" data-toggle="tooltip" title="Editar">
                            <i class="fas fa-pencil-alt" style="color:blue"></i>
                        <a href="" class="btn btn-danger-outline"
                            data-toggle="modal" data-target="#fm-modal-grid-{{user.pk}}"
                            data-tt="tooltip" title="Desabilitar usuário">
                            <i class="fa fa-user-times" aria-hidden="true" style="color:red"></i>
                        </a>
                        <div class="modal fade" id="fm-modal-grid-{{user.pk}}" tabindex="-1"
                             role="dialog" aria-labelledBy="fm-modal-grid-{{user.pk}}"
                            aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header" style="background-color: rgb(78,115,223);">
                                        <h5 class="modal-title" id=""><strong><font color="white">Desativar usuario</font></strong></h5>
                                        <button class="close" data-dismiss="modal" aria-label="Cerrar">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container-fluid">
                                            <div class="row">
                                                <div class="col-12 col-sm-6">
                                                    <p><strong>Você tem certeza que deseja desativar o usuário:</strong> {{ user }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal-footer" style=" background-color: rgb(78,115,223);">
                                        <form action="{% url 'usuario:mudar_ativo_status' ativo_status=0 usuario=user.pk %}" method="POST">
                                               {% csrf_token %}
                                               <button class="btn btn-danger">Desativar</button>
                                        </form>
                                        <button class="btn btn-dark"  data-dismiss="modal">Cancelar</button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
             {% endfor %}

             </tbody>
         </table>
    {% else %}
         <p>Não há Usuarios cadastrados!</p>
    {% endif %}
    <br>

{% endblock %}

LabParasitologia/templates/Usuario/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo %}
	<h1>Login</h1>
{% endblock %}

{% block content %}
  <div class="container">

    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-success" name="" value="Login">
    </form>
  </div>
{% endblock %}

LabParasitologia/templates/Usuario/user_detail.html
{% extends "base.html" %}

{% block titulo %}
	Informações do usuário
{% endblock %}


{% block content %}

    <div class="jumbotron">
        <h5>Usuario: {{ user.username }} </h5>
	    <h5>Nome: {{ user.first_name }} {{ user.last_name }} </h5>
        <h5>E-mail {{ user.email }} </h5>
    </div>

{% endblock %}

LabParasitologia/templates/Usuario/usuarios_inativos.html
{% extends "base.html" %}

{% block arquivos_js_css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Amostra/css/list_style.css' %}"/>
<script src="{% static 'Amostra/js/list_js.js' %}"></script>
{% endblock %}

{% block titulo %}
	  Usuários Inativos
{% endblock %}

{% block content %}



    {% if lista_user %}
         <table id="dtBasicExample" class="table" cellspacing="0" width="100%">
          <thead >
            <th scope="col">#</th>
            <th>Nome</th>
            <th>Usuario</th>
            <th>E-mail</th>
            <th></th>
          </thead>

             <tbody>
             {% for user in lista_user %}
                <tr>
                 <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ user }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email}}</td>
                    <td>
                        <a href="" class="btn btn-danger-outline"
                            data-toggle="modal" data-target="#fm-modal-grid-{{user.pk}}">
                            <i class="fa fa-user-plus" aria-hidden="true" style="color:green"></i>
                        </a>
                        <div class="modal fade" id="fm-modal-grid-{{user.pk}}" tabindex="-1"
                             role="dialog" aria-labelledBy="fm-modal-grid-{{user.pk}}"
                            aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                     <div class="modal-header" style="background-color: rgb(78,115,223);">
                                         <h5 class="modal-title" id=""><strong><font color="white">Ativar usuário</font></strong></h5>
                                        <button class="close" data-dismiss="modal" aria-label="Cerrar">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container-fluid">
                                            <div class="row">
                                                <div class="col-12 col-sm-6">
                                                    <p><strong>Você tem certeza que deseja ativar o usuário:</strong> {{ user }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal-footer" style="background-color: rgb(78,115,223);">
                                        <form action="{% url 'usuario:mudar_ativo_status' ativo_status=1 usuario=user.pk %}" method="POST">
                                               {% csrf_token %}
                                               <button class="btn btn-success">Ativar</button>
                                        </form>
                                        <button class="btn btn-dark" data-dismiss="modal">Cancelar</button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
             {% endfor %}

             </tbody>
         </table>
    {% else %}
         <p>Não há usuários inativos no sistema</p>
    {% endif %}
{% endblock %}